[package]
name = "server"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[[bin]]
name = "server"

[dependencies]
grpc = "0.6.*"
tls-api = "0.1.*"
tls-api-native-tls = "0.1.*"
httpbis = "0.7.*"

implementation = { path = "../implementation" }
