[workspace]
members = ["../lpd", "bincode", "wire", "brontide", "shachain"]

[package]
name = "lpd"
version = "0.0.0"
description = "The implementation of a Lightning Network node"
license = "Apache-2.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[lib]
name = "lpd"

[[example]]
name = "wasm-basic"
crate-type = ["cdylib"]

[[example]]
name = "wasm-runner"

[dependencies]
wire = { path = "wire" }
brontide = { path = "brontide" }
shachain = { path = "shachain" }

rand = "0.5.4"
secp256k1 = "0.9.2"
hex = "0.3.2"

[dev-dependencies]
serde_derive = "1.0.70"