[package]
name = "wallet"
version = "0.1.0"
authors = ["evgeniy.scherbina <evgeniy.scherbina@bitfury.com>"]

[dependencies]
bitcoin = "0.18"
bitcoin_hashes = "0.3"
secp256k1 = "0.12"
hex = "0.3.2"
wire = { path = "../wire" }
