[package]
name = "common-types"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
dependencies = { path = "../dependencies" }
binformat = { path = "../binformat" }

[features]
testing = []
