[package]
name = "interface"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[dependencies]
grpc = "0.6.*"
protobuf = "2.2.*"

[build-dependencies]
protoc-rust-grpc = "0.6.*"
