[package]
name = "channel"
version = "0.0.0"
authors = ["Mykola Sakhno <mykola.sakhno@bitfury.com>"]
description = "The implementation of a Lightning channel"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "channel"

[dependencies]
dependencies = { path = "../dependencies" }
