[package]
name = "bitcoin-types"
version = "0.1.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
common-types = { path = "../common-types" }
dependencies = { path = "../dependencies" }