[package]
name = "processor"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@bitfury.com>"]
edition = "2018"

[dependencies]
either = "1.5"
tokio = "0.1"
binformat = { path = "../binformat" }
wire = { path = "../wire" }
