[package]
name = "routing"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[dependencies]
secp256k1 = "0.9.2"
interface = { path = "../rpc/interface", optional = true }
wire = { path = "../wire" }
binformat = { path = "../binformat" }
brontide = { path = "../brontide" }
common-types = { path = "../common-types" }
bitcoin-types = { path = "../bitcoin-types" }
chrono = "0.4.5"
rand = "0.5.4"
specs = "0.12.2"
specs-derive = "0.2.0"
shred = "0.7.0"
shred-derive = "0.5.0"
rayon = "1.0.2"
tokio = "0.1.11"
rocksdb = "0.10.1"
serde = "1.0.80"
serde_derive = "1.0.80"
hex = "0.3.2"

[dev-dependencies]
hex-literal = "0.1.1"
brontide = { path = "../brontide", features = ["testing"] }
wire = { path = "../wire", features = ["testing"] }

[features]
rpc = ["interface"]
