[package]
name = "connection"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@bitfury.com>"]
edition = "2018"

[dependencies]
brontide = { path = "../brontide" }
wire = { path = "../wire" }
state = { path = "../state" }
secp256k1 = "0.12"

tokio = "0.1"
futures = "0.1"
rayon = "1.0"

rocksdb = "0.10"
serde = "1.0"
serde_derive = "1.0"

specs = "0.12"
specs-derive = "0.2"
shred = "0.7"
shred-derive = "0.5"

either = "1.5"

hex = "0.3.2"
