[package]
name = "shachain"
version = "0.1.0"
authors = ["evgeniy.scherbina <evgeniy.scherbina@bitfury.com>"]
edition = "2018"

[dependencies]
dependencies = { path = "../dependencies" }
common-types = { path = "../common-types" }
