[package]
name = "channel_machine"
version = "0.1.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]
edition = "2018"

[dependencies.wire]
path = "../wire"

[dependencies.channel]
path = "../channel"

[dependencies]
dependencies = { path = "../dependencies" }
