[package]
name = "implementation"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]
edition = "2018"

[dependencies]
grpc = "0.6.*"

interface = { path = "../interface" }
wire = { path = "../../wire" }
connection = { path = "../../connection", features = ["rpc"] }
state = { path = "../../state" }

futures = "0.1"
hex = "0.3"
secp256k1 = "0.12"
