[package]
name = "binformat"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@bitfury.com>"]
edition = "2018"

[dependencies]
bincode = { path = "../bincode" }
flate2 = "1.0"
serde = "1.0"
secp256k1 = { version = "0.12", optional = true }
